language: ruby
rvm:
  - 2.2.0

branches:
  except:
    - lazy_basic
    - lazy_mega

env:
  global:
    - TZ="US/Eastern"

addons:
  code_climate:
    repo_token:
      secure: "ctl8kfDYf8EH/Gwr7ZU5yqjV49U7TaMyHNnKat+4/5+LjE0ZDfyQyFQn/7ELJJXhmRQW90rRlZOqiDSjf2jAawl1xgxdL7ltCUAejLX4C3aykFMLTfOnV78cVgxbVbrHiCFqoKIclIFwe+jk2KCX7sHRCHxt/URIobY6H5zXv/o="

bundler_args: --without development production

script:
  - bundle exec rspec

deploy:
  provider: heroku
  api_key:
    secure: "nxESZKkn2z6LLkyE3C+oEr0iP7X2d2yj6qgYOZyrpMiZIpDG0+zHngUNFdtAfJfACfAVSpnNjS17hUIQtAG0x4aBDP8f5zDoJO/ytmQNp+M6KmxR4p3v9XnckEs+Hqmk9M0ITw1gTxB7Eznzjp7cJwZg7elUAXBfkUPeEzVtQ38="
  app:
    master: tc359-holidays-form
  on:
    repo: chrisvfritz/holidays_form
